version: '3.8'

services:
  app:
    build: .
    restart: always
    env_file: .env
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "81:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot_data:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_data:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  certbot_data: